/**
 * PAJESYSTEMS - Master Wix Velo SSO Integration
 * Version Control: GitHub (Local Repo: c:\aaa_appPAJEclub)
 * Context: Do not edit this file directly in Wix without mirroring back to GitHub.
 * 
 * Objective: Intercepts Wix login/booking flows and bridges them to the Locaweb Django SSO.
 */

import wixUsers from 'wix-users';
import wixLocation from 'wix-location';
import { fetch } from 'wix-fetch';

const SSO_ENDPOINT = "https://sso.pajesystems.com/api/v1/auth/verify";
const WIX_PREMIUM_DOOR_ID = "btnAcessoAssinantes";

$w.onReady(function () {
    // Escuta o clique na "PORTA 2" (Acesso Assinantes)
    $w(`#${WIX_PREMIUM_DOOR_ID}`).onClick((event) => {
        handleSSORedirect();
    });
});

/**
 * Redireciona o usuário para o servidor SSO próprio da Locaweb
 * enviando os parâmetros de retorno para o Wix após o login bem-sucedido.
 */
function handleSSORedirect() {
    const returnUrl = encodeURIComponent(wixLocation.url);
    const ssoLoginUrl = `https://sso.pajesystems.com/login?redirect=${returnUrl}&client=wix_premium`;

    // Redireciona o navegador do usuário
    wixLocation.to(ssoLoginUrl);
}

/**
 * Função utilitária para validar tokens JWT recebidos do SSO da Locaweb
 * caso o Wix precise consumir APIs restritas do HDsys.
 */
export async function validatePajeToken(jwtToken) {
    try {
        const response = await fetch(SSO_ENDPOINT, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${jwtToken}`
            }
        });

        if (response.ok) {
            const data = await response.json();
            return { valid: true, tier: data.tier, user: data.user_id };
        }
        return { valid: false };
    } catch (error) {
        console.error("SSO Connection Error:", error);
        return { valid: false };
    }
}
